[package]
authors     = [ "Mauro Lacy <mauro@lacy.com.es>" ]
description = "Protobug parsing for Injective Protocol"
edition     = "2021"
license     = "Apache-2.0"
name        = "injective-protobuf"
readme      = "README.md"
repository  = "https://github.com/InjectiveLabs/cw-injective/tree/dev/packages/injective-protobuf"
version     = "0.2.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
protobuf-codegen-pure = "2"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = [ "cosmwasm-std/backtraces" ]

[dependencies]
cosmwasm-std    = { version = "1.5.0", features = [ "abort", "cosmwasm_1_2", "cosmwasm_1_3", "cosmwasm_1_4", "iterator", "stargate" ] }
protobuf        = { version = "2", features = [ "with-bytes" ] }

[dev-dependencies]
cosmwasm-schema = { version = "1.5.0" }
