[package]
name = "atomic-order-example"
version = "0.1.0"
authors = ["Antoni Mysliborski <antoni@toptal.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer-arm64:0.12.11
"""

[dependencies]
cosmwasm-std        = { version = "1.2.7", features = [ "abort", "iterator", "stargate" ] }
cosmwasm-storage    = { version = "1.2.7", features = [ "iterator" ] }
cw-storage-plus     = { version = "0.16.0" }
cw2                 = { version = "0.16.0" }
cw-utils            = { version = "0.16.0" }
schemars            = { version = "0.8.8", features = [ "enumset" ] }
serde               = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror           = { version = "1.0.31" }
injective-cosmwasm = { version = "0.2.16", path= "../../packages/injective-cosmwasm" }
injective-math = { version = "0.2.2", path = "../../packages/injective-math" }
protobuf            = { version = "2.28.0", features = ["with-bytes"] }
injective-protobuf = { path = "../../packages/injective-protobuf", version = "0.2.1" }

[dev-dependencies]
cosmwasm-schema     = { version = "1.2.7" }
cw-multi-test       = { version = "0.16.2" }
